### ISSUE TITLE
Crash Report: Failed to create an instance

### ISSUE THREAD

**Issue by oldManLemon** [gomorpheus/terraform-provider-morpheus#60]
Created instance: 
Attempted to create an instance with Terraform module. 

All details and provided ID's were accepted and as I saw in the crash report if seemed to have found all the correct resources. Then I get the golang memory pointer crash see below.

I am happy to provide more details if needed. 

Error Message
`morpheus_vsphere_instance.tf_example_vsphere_instance: Creating...
morpheus_vsphere_instance.tf_example_vsphere_instance: Still creating... [10s elapsed]
morpheus_vsphere_instance.tf_example_vsphere_instance: Still creating... [20s elapsed]
╷
│ Error: Plugin did not respond
│
│   with morpheus_vsphere_instance.tf_example_vsphere_instance,
│   on instances.tf line 38, in resource "morpheus_vsphere_instance" "tf_example_vsphere_instance":
│   38: resource "morpheus_vsphere_instance" "tf_example_vsphere_instance" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-morpheus_v0.6.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbda3e1]

goroutine 67 [running]:
github.com/gomorpheus/terraform-provider-morpheus/morpheus.resourceVsphereInstanceCreate({0xf05288, 0xc000114c60}, 0x0?, {0xdad0e0?, 0xc00032a0c0?})
        github.com/gomorpheus/terraform-provider-morpheus/morpheus/resource_vsphere_instance.go:290 +0x4e1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00044a700, {0xf052c0, 0xc0007d5ef0}, 0xd?, {0xdad0e0, 0xc00032a0c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00044a700, {0xf052c0, 0xc0007d5ef0}, 0xc00037d5f0, 0xc000373900, {0xdad0e0, 0xc00032a0c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003171d0, {0xf052c0?, 0xc0007d5dd0?}, 0xc0003c1220)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00036aaa0, {0xf052c0?, 0xc0007d55c0?}, 0xc0003ec700)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd5dfe0?, 0xc00036aaa0}, {0xf052c0, 0xc0007d55c0}, 0xc0003ec690, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003fa000, {0xf07e20, 0xc0002e0680}, 0xc000589b00, 0xc0004641b0, 0x14037a0, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0003fa000, {0xf07e20, 0xc0002e0680}, 0xc000589b00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-morpheus_v0.6.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

Crash Report Link: https://pastebin.com/KCGm4SBx with Terraform Debug on.

**Comment by martezr** [comment]
It looks like the error was thrown because the defined resource pool could not be found. I'm looking into why an error wasn't thrown to indicate the the resource pool data resource didn't return a result.
